### ISSUE TITLE
help: beaker.session.id cookie

### ISSUE THREAD

**Issue by jiaweih** [pacificclimate/pdp#10]
I'm trying to use **wget** to download data from the website http://tools.pacificclimate.org/dataportal/downscaled_gcms/map/. To make that happen, I need to **"find the beaker.session.id cookie for the domain tools.pacificclimate.org"** as mentioned in one relevant website. But how to find the beaker.session.id cookie? Thank you!

**Comment by basilveerman** [comment]
Hi jiaweih,

[Here](http://www.wikihow.com/View-Cookies) is a site that shows you how to view your cookies on all major browsers.

**Comment by jiaweih** [comment]
Thank you, basilveerman! I was using Safari, and it didn't work with the method. Anyway, it works in Chrome.

**Comment by basilveerman** [comment]
Good to hear!
