### ISSUE TITLE
Requesting nonexistent timestamps causes downloads to hang

### ISSUE THREAD

**Issue by corviday** [pacificclimate/pdp#106]
A request is made for timestamps after the last timestamp in the file, like this one:
```
/data/downscaled_gcms/pr_day_BCCAQv2+ANUSPLIN300_CanESM2_historical+rcp85_r1i1p1_19500101-21001231.nc.nc?pr[0:55152][120:122][323:325]&
```
This file has only 55115 timestamps. When the responder reaches the end of the available timestamps, it just sits with the file open and does nothing. Haproxy will kill the connection eventually, and the user will see a failed download. The worker and the memory used to open the file remain unavailable for new downloads.

What should probably happen instead: HTTP 400 response if a request for data outside the file is received.

**Comment by corviday** [comment]
I've been having reproducing this bug under controlled conditions. I think my earlier tests to confirm it may have been a subset of a different bug, https://github.com/pacificclimate/pdp/issues/107

**Comment by jameshiebert** [comment]
I think that it's highly likely that this is a symptom of [this bug](https://github.com/pacificclimate/pydap.handlers.hdf5/issues/3) in the HDF5 handler. Can we close this in favor of focusing the discussion over there?
