### ISSUE TITLE
Non-zero start time indexes sometimes hang

### ISSUE THREAD

**Issue by corviday** [pacificclimate/pdp#107]
Some downloads with non-zero starting time indexes hang. For example, this download succeeds:
```
/downscaled_gcms/tasmin_day_BCCAQv2+ANUSPLIN300_CCSM4_historical+rcp45_r2i1p1_19500101-21001231.nc.nc?tasmin[2:7][32:32][739:739]
```

While this one, which differs only in the time slice, hangs when nearly finished:
```
/downscaled_gcms/tasmin_day_BCCAQv2+ANUSPLIN300_CCSM4_historical+rcp45_r2i1p1_19500101-21001231.nc.nc?tasmin[2:8][32:32][739:739]
```

**Comment by corviday** [comment]
This issue seems to be triggered by a bug in [this script](https://github.com/pacificclimate/data-prep-actions/blob/86e2059d3b4c3126ebcaa1bdb1b1986114d2001d/actions/normalize-pdp-time/remove_time_offset.py), which was used while processing the BCCAQv2 files to correct files that had weird time data. 

I didn't notice while writing or running the time correction script, but it seems to unintentionally convert unlimited time dimensions to limited time dimensions. This means that files that were processed with the time-data-correction script have no record variables (netCDF variables that are associated with unlimited dimensions). 

The responder that serves the netCDF data [assumes there is at least one record dimension, and will hang if there isn't](https://github.com/pacificclimate/pydap.responses.netcdf/issues/4).

It's not yet clear to me why this doesn't affect _every_ data request made against a file with a limited time dimension. More testing is needed.

**Comment by ConorIA** [comment]
Before you make any major changes, I'll just mention that this bahaviour happened with the original BCCAQ files as well. I first wrote the chapter in question (https://gitlab.com/claut/man_ccia/blob/master/10-PCICdata.Rmd) back in summer/fall 2018 and hit that bug. The script you identified seems to be BCCAQv2-specific.

**Comment by corviday** [comment]
Thanks, that's good to know.

**Comment by corviday** [comment]
**An update:**

Thank you for your patience and your detailed error reports. We've found two different bugs in our netCDF-serving module that cause, in different cases, the downloading failures you have encountered:

1. A bug that affected serving files with no unlimited dimensions properly; the code would endlessly loop over an empty set of unlimited dimensions and the download would hang when almost complete. This affects the BCCAQv2 dataset, which is the only dataset we have at present in which some of the files do not have any unlimited dimensions. https://github.com/pacificclimate/pydap.responses.netcdf/issues/4
2. A bug relating to padding variable matrices to a multiple of four bytes, as required in the netCDF standards. This bug typically affects downloading an odd number of timesteps. The improperly-padded files would not be the length promised in the content header, causing the download to fail. https://github.com/pacificclimate/pydap.responses.netcdf/issues/6

We currently think we've solved the first and made some solid headway on the second, so hopefully the issues will be resolved soon.

**Comment by jameshiebert** [comment]
We've solved the even vs. odd issue and any other slowness, I believe, is related to [this problem](https://github.com/pacificclimate/pydap.handlers.hdf5/issues/3) in the HDF5 handler. Can we close this in favor of focusing the discussion over there?
