### ISSUE TITLE
Unable to read data downloaded from website

### ISSUE THREAD

**Issue by cuell** [pacificclimate/pdp#112]
Downloaded:
tasmax_day_BCCAQv2+ANUSPLIN300_ACCESS1-0_historical+rcp45_r1i1p1_19500101-21001231.nc 
for dates 1950/01/01 through 1959/12/31 from website. Trying to open the file in python with netCDF4 gives:
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-4-bd4055ae0773> in <module>
----> 1 ds = nc.Dataset(filename_nc)

netCDF4/_netCDF4.pyx in netCDF4._netCDF4.Dataset.__init__()

netCDF4/_netCDF4.pyx in netCDF4._netCDF4._ensure_nc_success()

OSError: [Errno -51] NetCDF: Unknown file format: b'/home/cuell/Data/CRC/Data/Test/tasmax_day_BCCAQv2+ANUSPLIN300_ACCESS1-0_historical+rcp45_r1i1p1_20000101-20191231.nc'

To double checked, opened in Panolpy. It opened, but when trying to view the data, got the attached error.

![error_pcic](https://user-images.githubusercontent.com/11698200/55343144-5c610800-545f-11e9-90bb-845c5d1c44aa.png)

**Comment by corviday** [comment]
Thank you for the detailed error report. I'll look into it.

**Comment by corviday** [comment]
I have been able to reproduce the error. Variable offset addresses in the downloaded file are invalid. For example, the offset address for longitude, which says how far into the file the longitude value begin, is `ed213224`, which interpreted according to the netCDF specifications as a 32-bit signed int, works out to the longitude values being present in the file starting at bit -316591580. Oops.

This behaviour would be reasonable in a netCDF file of more than 4GB - the 32 bit internal file addresses can only describe 4GB of memory space, so larger files have to be encoded differently - but the downloaded file is only 3.8GB, so it's quite puzzling.

Still working on a fix, but as far as I can tell, substantially smaller files do not have this problem, and if you need a temporary workaround, I would suggest downloading only five years of data at a time.

Thank you for your patience.

**Comment by jameshiebert** [comment]
We're pretty sure that this is a symptom of [this bug](https://github.com/pacificclimate/pydap.responses.netcdf/issues/2), so you can head over there for the technical details, if interested.

**Comment by cuell** [comment]
Thanks, everybody for your quick attention to this. I really appreciate it!

**Comment by jameshiebert** [comment]
Yeah no problem. Just FYI, the *code* is fixed, but we haven't yet deployed the new code to production. Watch for verison 2.7.0... still a couple other items that we want to roll into that milestone before we release and deploy.
