### ISSUE TITLE
Corrupted archive for Campbell River EC_raw station native_id 1021261

### ISSUE THREAD

**Issue by basilveerman** [pacificclimate/pdp#13]
This particular station returns a corrupt archive, yet there are many valid obs in the database.

[Download Link](http://tools.pacificclimate.org/dataportal/auth/agg/?from-date=YYYY%2FMM%2FDD&to-date=YYYY%2FMM%2FDD&input-polygon=MULTIPOLYGON%28%28%28-125.28207653408481+49.95961190336475%2C-125.2966924181377+49.951602891237414%2C-125.28045862027905+49.939653591295354%2C-125.25904256528572+49.95010831372428%2C-125.28207653408481+49.95961190336475%29%29%29&input-var=&network-name=EC_raw&input-freq=&data-format=nc&download-timeseries=Timeseries)

```sql
crmp=> select history_id, station_id, native_id, count(*) as obs_count from obs_raw natural join meta_history natural join meta_station where native_id = '1021261' group by history_id, station_id, native_id;
 history_id | station_id | native_id | count 
------------+------------+-----------+-------
        840 |        437 | 1021261   | 94061
       8363 |       6678 | 1021261   | 73064
(2 rows)
```

**Comment by basilveerman** [comment]
Error also appears in the [station listing page](http://tools.pacificclimate.org/dataportal/auth/pcds/raw/EC_raw/1021261)

**Comment by jameshiebert** [comment]
This is actually a *data* error, with a poor check on the error condition:

```sql
crmp=> select * from meta_station where native_id = '1021261';
 station_id | network_id | native_id |    min_obs_time     |    max_obs_time     
------------+------------+-----------+---------------------+---------------------
       6577 |         19 | 1021261   |                     | 
        437 |          1 | 1021261   | 1965-01-01 00:00:00 | 2004-10-31 00:00:00
       6678 |         19 | 1021261   | 2011-10-16 00:00:00 | 2012-02-14 21:00:00
(3 rows)

crmp=> select history_id, station_id, station_name, st_x(the_geom), st_y(the_geom) from meta_history where station_id in (6577, 437, 6678);
 history_id | station_id |      station_name      |       st_x        |       st_y       
------------+------------+------------------------+-------------------+------------------
       8363 |       6678 | Campbell River Airport | -125.273055555556 | 49.9519444444444
        840 |        437 | CAMPBELL RIVER A       |         -125.2708 |         49.95084
(2 rows)
```

The data model is such that meta_station is in a one-to-many relationship with meta_history, however, the data have multiple stations for one history. In particular station 6577 is completely spurrious and has no metadata in meta_history. Closing this issue, but will open a related issue for better error checking on the station search.
