### ISSUE TITLE
Remove hydro_stn_filters.js?

### ISSUE THREAD

**Issue by rod-glover** [pacificclimate/pdp#130]
`pdp/static/js/hydro_stn_filters.js` is not served by any portal (including `hydro_stn`), nor is it referenced anywhere else in code. It contains date filtering code that is superseded by the new calendar-aware code introduced in #116 . It looks like this file should be removed.

**Comment by rod-glover** [comment]
It also looks as if it may contain errors: it hits API endpoints of the form `pdp.app_root + '/apps/count_stations'` and `pdp.app_root + '/apps/record_length'` which AFAIK are not valid.

**Comment by corviday** [comment]
The hydro station portal also has a catalog that as far as I can tell is checked during tests, but not actually used by the portal.

**Comment by rod-glover** [comment]
Checked during what tests?

**Comment by corviday** [comment]
https://github.com/pacificclimate/pdp/blob/a31cb88128cba64b52aadf9b2ba87b0dd124fa00/tests/test_functional.py#L487

**Comment by corviday** [comment]
I'm working on the hydro station portal right now, so I removed hydro_stn_filters.js, but on further investigation and thought, I think the "unused" station catalog I mentioned in the previous comment is part of the direct pydap interface for scripting or power users, and thus functional even if not used by the frontend.
