### ISSUE TITLE
On "Reset Filters" map tiles disappear

### ISSUE THREAD

**Issue by faronium** [pacificclimate/pdp#147]
When I am using the [BC station data portal](https://data.pacificclimate.org/portal/pcds/map/) and click the Reset Filters button, all map tiles disappear and show a missing image symbol instead. When I then resupply a filtering date range, the map tiles reappear. Seems that what is shown on the map is contingent on the date including the base layers. The behaviour I would expect is that when I click on the Reset Filters button I get a map that looks like the original when the page first loads. That is zoomed out to BC wide and showing all stations. Instead of killing the date range, Reset Filters would be better off if it extended the date range back out to the fully available date range for data in BC.

**Comment by jameshiebert** [comment]
Hmm, that's annoying!

Yes, I can confirm that when the dates get set to empty, they are excluded from the filter parameters that gets sent to Geoserver in the WMS request. What gets returned actually isn't a missing image, it's an error:

```bash
$ curl 'https://tools.pacificclimate.org/geoserver/CRMP/wms?LAYERS=CRMP%3Acrmp_network_geoserver&TRANSPARENT=true&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&STYLES=&FORMAT=image%2Fpng&SRS=EPSG%3A3005&filter=%3Cogc%3AFilter%20xmlns%3Aogc%3D%22http%3A%2F%2Fwww.opengis.net%2Fogc%22%3E%3Cogc%3AAnd%3E%3Cogc%3AAnd%3E%3Cogc%3APropertyIsGreaterThanOrEqualTo%3E%3Cogc%3APropertyName%3Emax_obs_time%3C%2Fogc%3APropertyName%3E%3Cogc%3ALiteral%3E%3C%2Fogc%3ALiteral%3E%3C%2Fogc%3APropertyIsGreaterThanOrEqualTo%3E%3Cogc%3APropertyIsLessThanOrEqualTo%3E%3Cogc%3APropertyName%3Emin_obs_time%3C%2Fogc%3APropertyName%3E%3Cogc%3ALiteral%3E%3C%2Fogc%3ALiteral%3E%3C%2Fogc%3APropertyIsLessThanOrEqualTo%3E%3C%2Fogc%3AAnd%3E%3C%2Fogc%3AAnd%3E%3C%2Fogc%3AFilter%3E&BBOX=1467694,1177526.75,2035630,1745462.75&WIDTH=256&HEIGHT=256' -H 'User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0' -H 'Accept: image/webp,*/*' -H 'Accept-Language: en-CA,en-US;q=0.7,en;q=0.3' --compressed -H 'Referer: https://data.pacificclimate.org/portal/pcds/map/' -H 'DNT: 1' -H 'Connection: keep-alive'
```
```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><!DOCTYPE ServiceExceptionReport SYSTEM "http://pizza.pcic.uvic.ca:8080/geoserver/schemas/wms/1.1.1/WMS_exception_1_1_1.dtd"> <ServiceExceptionReport version="1.1.1" >   <ServiceException code="internalError">
      Rendering process failed
java.io.IOExceptionorg.postgresql.util.PSQLException: ERROR: invalid input syntax for type timestamp: &quot;&quot;
  Position: 184
ERROR: invalid input syntax for type timestamp: &quot;&quot;
  Position: 184
</ServiceException></ServiceExceptionReport>
```

Given that this UI is being completely replaced with a [new ReactJS version](https://github.com/pacificclimate/station-data-portal), we will have to consider whether it's worth fixing this in the near term vs. simply replacing the full app.
