### ISSUE TITLE
Invalid map date on gridded observations portal

### ISSUE THREAD

**Issue by corviday** [pacificclimate/pdp#153]
![invaliddate](https://user-images.githubusercontent.com/4512605/71746951-37048e80-2e23-11ea-8954-5b0c1f481741.png)

The Gridded Observations portal, but not most portals, is showing a "date" of `NaN/NaN/NaN` on the map display.

**Comment by jameshiebert** [comment]
Relevant code seems to be [here](https://github.com/pacificclimate/pdp/blob/master/pdp/static/js/gridded_observations_map.js#L74).

**Comment by jameshiebert** [comment]
Looks like a date parsing issue:

```js
$ nodejs 
> time="1997-3-17T00:00:00Z"
'1997-3-17T00:00:00Z'
> var d = new Date(time);
undefined
> d
Invalid Date
> 
```
