### ISSUE TITLE
Separate configuration from pdp/__init__.py

### ISSUE THREAD

**Issue by jameshiebert** [pacificclimate/pdp#17]
Portal config options should be separated out from `pdp/__init__.py` such that:

* all portal pages should be moved into `portal/*.py` files
* nothing is actually *executed* in `__init__.py`

  * e.g. the test suite should be able to import symbols from `pdp` and select what it executes (based on what marks/fixtures are selected at run time)

* the most commonly used config options are factored out to a yaml config file

  * app_root
  * geoserver_url
  * ncwms_url
  * auth_required (True|False) (this may become moot, eventually)
  * jsmin (True|False)
  * pcds_dsn
  * mm_dsn

**Comment by basilveerman** [comment]
Fixed with c07b87f61136a35120d352b95f7147248b9d169f
