### ISSUE TITLE
Keremos Municipal Office - Wrong Location

### ISSUE THREAD

**Issue by naberard** [pacificclimate/pdp#202]
the keremos data (Station 2617, ENV-AQN) has the coordinates placing it in the wrong location (well north of the actual town of Keremos)

![image](https://user-images.githubusercontent.com/80712676/111204014-edfdad80-8582-11eb-9b7c-412044837f7c.png)

**Comment by jameshiebert** [comment]
Yeah, I'd agree that that location is not very close to the town, or... anything really. That said, that *is* the recorded location that we have for it from the data provider, and it's not uncommon for stations to be far afield (particularly for air quality monitoring). And it's not a very long record, so its value is kind of questionable (from a climate perspective) anyway.

@faronium do you have any comment on this?

**Comment by faronium** [comment]
Hmmm, yeah this is suspect given that the name of the station is Keremeos Municipal Office and the AQN typically puts stations in places where people are to monitor the air quality for them. The elevation also corresponds to the townsite. I'll ask the network operator to see if he has a different location for this site than we do. I also can confirm that the location that we have for it is the one we received from the MoE: "49 20 58","119 50 10","423". Those are DMS coordinates.

**Comment by faronium** [comment]
I got new coordinates from the network manager @naberard and @jameshiebert . It's a best guess as their records are wrong at the most basic level, so the site was google-earthed... Those coords are now in the database and the station plots in Downtown Keremeos.

49.204702/-119.827510

![Screenshot from 2021-03-24 14-01-54](https://user-images.githubusercontent.com/11469553/112382881-a1fce800-8ca9-11eb-927e-92217bfe9b10.png)

**Comment by jameshiebert** [comment]
Cool, thanks!
