### ISSUE TITLE
Rename downscaled datasets

### ISSUE THREAD

**Issue by jameshiebert** [pacificclimate/pdp#257]
This should be very simple, but the downscaled datasets are going to be going by new names as follows:

+ Canadian Downscaled Climate Scenarios – Univariate (CMIP5): CanDCS-U5
+ Canadian Downscaled Climate Scenarios – Univariate (CMIP6): CanDCS-U6
+ Canadian Downscaled Climate Scenarios – Multivariate (CMIP6): CanDCS-M6

We should change these references in the UI code.

**Comment by corviday** [comment]
I ask Charles whether we should renamed the [BCCAQ1 portal as well](https://data.pacificclimate.org/portal/downscaled_gcms_archive/map/), or change the text on the links from the BCCAQ2 to the BCCAQ1 portal; he said no.
