### ISSUE TITLE
Respect alternative calendars in datepicker

### ISSUE THREAD

**Issue by basilveerman** [pacificclimate/pdp#27]
The current implementation converting netCDF time in "<units> since <start date>" to jquery datepicker assumes a standard calendar. This results in incorrect data selection when converting back into netCDF time index.

The solution would be to parse the calendar type from the das report and make [cfTime](https://github.com/pacificclimate/pdp/blob/master/pdp/static/js/pdp_raster_map.js#L7) calendar aware, but this creates another problem: the jquery datepicker (and other js calendars) only represents a standard calendar. This would result in inconsistencies and unavailable dates with 360 and 365 day calendars. For this, we would need to either write our own calendar aware datepicker, notify the user of the discrepancy, or just use text input fields.

**Comment by basilveerman** [comment]
Dug through the logs for the past calendar year to determine user date selection statistics.

Start time requests
------------------------

Index | Count | Percentage of reqs
------- | -------- | -------------
0 | 2502 | 87
7305 | 148 | 5
11323 | 74 | 2
33238 | 30 | 1
18262 | 30 | 1
22280 | 18 | 0

End time requests
-----------------------

Index | Count | Percentage of reqs | Notes
------- | -------- | -------------------------- | --------
55152 | 1271 | 44 | standard cal max
55115 | 478 | 16 | 365-day cal max
54787 | 367 | 12 | hydro max w/standard cal
12 | 320 | 11 | prism max
54000 | 82 | 2 |  360-day cal max
54359 | 43 | 1 | 

Data sources
-----------------

Source | Calendar
---------- | -----------
BCSD | 33 standard
BCCAQ | 11 standard, 5 - 360 day, 17 - 365-day
VIC output | 29 standard
VIC input | 23 standard

**Comment by jameshiebert** [comment]
Nice work! This tells us that about 85% of our downloads are for the full time period, which is a *really* good thing to know. We should probably prioritize a "download full timeseries" link somewhere to satisfy the bulk of the requests. I'll write up an enhancement issue for that.
