### ISSUE TITLE
Error when attempting to open/unzip archive

### ISSUE THREAD

**Issue by mschnorb** [pacificclimate/pdp#29]
Linux reports the following error when I attempt to unzip an archive of station data (using the command "unzip pcds_data.zip") that was downloaded from the PCDS:

"Archive:  pcds_data.zip
  End-of-central-directory signature not found. Either this file is not a zipfile, or it constitutes one disk of a multi-part archive.  In the latter case the central directory and zipfile comment will be found on the last disk(s) of this archive.
note:  pcds_data.zip may be a plain executable, not an archive
unzip:  cannot find zipfile directory in one of pcds_data.zip or pcds_data.zip.zip, and cannot find pcds_data.zip.ZIP, period."

On a Windows machine I get the following error:

![error](https://cloud.githubusercontent.com/assets/9890345/8170351/e93b2bb0-1364-11e5-90a9-bfdbabebb063.png)

The file was downloaded with the following filter options:
Date Range: 1980/01/01 to 2015/06/15
Climate Variables: Snowfall Amount
Network Name: All
Observation Frequency: Hourly

The output format was NetCDF timeseries. 

The file/archive in question is located at atlas:/home/data/projects/hydrology/vic_gen2/input/climate_parameters/temp_thresholds/data/hour/pcds_data.zip

**Comment by basilveerman** [comment]
Request comes in: 142.104.194.121 - - [15/Jun/2015:14:00:25 -0700] "GET /dataportal/data/pcds/agg/?from-date=1980%2F01%2F01&to-date=2015%2F06%2F15&input-polygon=&input-var=thickness_of_snowfall_amount&network-name=&input-freq=1-hourly&data-format=nc&download-timeseries=Timeseries HTTP/1.1" 200 39851904 "http://tools.pacificclimate.org/dataportal/pcds_map/map/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.124 Safari/537.36"

Apache error log: [Mon Jun 15 14:48:26 2015] [error] [client 127.0.1.1] (70007)The timeout specified has expired: Error reading chunk

Supervisor pdp_backend stdout: Exception ValueError: 'I/O operation on closed file' in <bound method ZipFile.__del__ of <zipfile.ZipFile object at 0x1c355490>> ignored

**Comment by basilveerman** [comment]
Looks like some extra log statements made it into the released of pupynere-pdp 1.1.3. These caused supervisor to echo all data back into log files and hit the 300s proxy timeout in Apache. Log statements have been removed in the installed and released versions of pupynere-pdp 1.1.3. Testing in progress.

**Comment by jameshiebert** [comment]
@basilveerman can you link to the extra logging in [pacificclimate/pupynere-pdp](https://github.com/pacificclimate/pupynere-pdp) in question? I see very little logging ([like one place](https://github.com/pacificclimate/pupynere-pdp/blob/master/pupynere.py#L481)) in the package...

**Comment by basilveerman** [comment]
@jameshiebert The log statements were in my code when I built the sdist and pushed to pypiserver, but never in the repo. You can see the result of this in /var/log/supervisord/pdp_backend-stdout---supervisor-*.

**Comment by basilveerman** [comment]
Errors again. Stopped after 119.3MB. Previous test resulted in only 39.8MB.

Request:
142.104.200.234 - - [15/Jun/2015:23:10:15 -0700] "GET /dataportal/data/pcds/agg/?from-date=YYYY%2FMM%2FDD&to-date=YYYY%2FMM%2FDD&input-polygon=&input-var=thickness_of_snowfall_amount&network-name=&input-freq=1-hourly&data-format=nc&download-timeseries=Timeseries HTTP/1.1" 200 119462989 "http://tools.pacificclimate.org/dataportal/pcds_map/map/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.125 Safari/537.36"

Apache Error log:
[Mon Jun 15 22:54:55 2015] [error] [client 142.104.200.234] (70007)The timeout specified has expired: proxy: error reading status line from remote server pizza.pcic.uvic.ca:8003
[Mon Jun 15 22:54:55 2015] [error] [client 142.104.200.234] proxy: Error reading from remote server returned by /dataportal/data/pcds/agg/
[Mon Jun 15 22:56:27 2015] [error] [client 142.104.200.234] (70007)The timeout specified has expired: proxy: error reading status line from remote server pizza.pcic.uvic.ca:8003, referer: http://tools.pacificclimate.org/dataportal/pcds_map/map/
[Mon Jun 15 22:56:27 2015] [error] [client 142.104.200.234] proxy: Error reading from remote server returned by /dataportal/data/pcds/agg/, referer: http://tools.pacificclimate.org/dataportal/pcds_map/map/

Backend error log:
[2015-06-16 00:10:15 +0000] [9555] [CRITICAL] WORKER TIMEOUT

**Comment by doylejg** [comment]
Any more insight on this bug? I have the same outcome as OP from a timeseries requst. My file request is as follows:

http://tools.pacificclimate.org/dataportal/data/pcds/agg/?from-date=2011%2F02%2F01&to-date=2011%2F02%2F28&input-polygon=&input-var=&network-name=&input-freq=&data-format=nc&cliptodate=cliptodate&download-timeseries=Timeseries

Furthermore, the download speeds are extremely slow. Is this to do with the apache throwing errors? My dataset is 3.5MB.

**Comment by basilveerman** [comment]
Hi doylejg,

I have taken a look into this and while it may appear to have the same results, the cause is different on our side. I'll open a new bug report and reference it here so you can link to it.

This bug was a result of aggressive timeouts and was solved by relaxing them.
