### ISSUE TITLE
error with rain gauge reporting for Environment Canada and BCHydro gauges

### ISSUE THREAD

**Issue by cooksonh** [pacificclimate/pdp#38]
I've been using the 24 hour accumulation of rain gauge data from EC and BCH gauges on PCIC. However, after much analysis and comparison to satellite, reanalysis, radar and EC's past weather data, I've determined that the 24 hour accumulations are reported at incorrect (or misleading) times. For example, the precipitation accumulation reported at 00Z on Feb 3, 2011 is actually the 24 hour precipitation accumulation throughout the day on February 3rd, 2011- from 00Z Feb 3- 00Z Feb 4. These should have one day added to the reporting time. I'm not sure about the other gauges from PCIC- can you confirm that these are also being reported the same way?

**Comment by jameshiebert** [comment]
PCIC archives and serves up data as it is reported by the collecting agencies. The [CRMP partners](http://www2.gov.bc.ca/gov/content/environment/research-monitoring-reporting/monitoring/weather-climate) differ in what they consider to be the "climatological day". Sometimes it's 00Z-00Z, sometimes it's 06Z-18Z, sometimes is 6am-6pm local time. If your requirements are localized enough in time and space that you need to differentiate between these, then this product may not meet your needs. Even EC is fairly vague on the exact timing of climatological observations:

>  At locations with no hourly observations, observation times are *generally morning and evening*.

(my emphasis). You'll definitely want to read [EC's technical documentation](http://climate.weather.gc.ca/prods_servs/documentation_index_e.html#dly) carefully and let that inform whether the product will meet your needs.

But from our end, we simply report the dates with which EC has attributed the data.

@faronium would you be willing to comment further? If not I recommend that we close this issue unless there is a demonstrable software bug.
