### ISSUE TITLE
Time variable incomplete when downloading netCDF file

### ISSUE THREAD

**Issue by mschnorb** [pacificclimate/pdp#39]
Downloaded spatial-temporal data from the "Statistically Downscaled Climate Scenarios" portal with the following settings:
+ Spatial extent: BC (lat = 158, lon = 310; see attached figure)
+ Dataset: historical+rcp85/BCSD+ANUSPLIN300+CanESM2/tasmax
+Period: 1950/01/01 to 2100/12/31 (55152 days)
+ Time of request: ~ 09:45 PDT
+ IP address: 142.104.194.119

Expected tasmax data on a 158 x 310 x 55152 hyper cube with the time variable increasing monotonically from t[0] to t[55151] days since 1950-01-01 00:00:00.

The downloaded netCDF file contained the necessary dimensions, but values for the time variable only increase monotonically from t[0]=0 to t[2146]=2146 and all remaining values are zero (i.e. t[12147:55151] = 0).

![portal_screen_shot](https://cloud.githubusercontent.com/assets/9890345/15257161/deabec48-18f9-11e6-8f28-77986a5bf772.png)

**Comment by jameshiebert** [comment]
Do you still have the ldownload URL in your browser history? If so, could you add it to the ticket and we'll have a look.

**Comment by mschnorb** [comment]
http://tools.pacificclimate.org/dataportal/data/downscaled_gcms/pr+tasmax+tasmin_day_BCSD+ANUSPLIN300+CanESM2_historical+rcp85_r1i1p1_19500101-21001231.nc.nc?tasmax[0:55151][81:238][13:322]&

**Comment by mschnorb** [comment]
Woops.

http://tools.pacificclimate.org/dataportal/data/downscaled_gcms/pr+tasmax+tasmin_day_BCSD+ANUSPLIN300+CanESM2_historical+rcp85_r1i1p1_19500101-21001231.nc.nc?tasmax[0:55151][81:238][13:322]&

**Comment by basilveerman** [comment]
@mschnorb Is the *data* valid when you look at it after the time values become zero?

**Comment by mschnorb** [comment]
The data exist beyond t=2146, but the values are also zero.

**Comment by mschnorb** [comment]
More details. During the "valid" portion of the record, data values in cells outside the data extent (e.g. ocean cells) are equal to missing_value, whereas during the"invalid" period all cells have value = 0.

**Comment by basilveerman** [comment]
@jameshiebert This sounds like apache proxy and/or gunicorn timeouts. I thought we had 'solved' that ages ago but perhaps not.

**Comment by jameshiebert** [comment]
Yeah, proxy timeout sounds likely. I can re-download that dataset w/ no problems, so it's definitely a transient problem. Markus, feel free to just download it again. Basil did you examine the gunicorn logs at all?

**Comment by basilveerman** [comment]
Nope, just noticed the similar symptoms. If it's an Apache timeout we should be seeing something like

```
[Mon Jun 15 22:54:55 2015] [error] client 142.104.200.234The timeout specified has expired: proxy: error reading status line from remote server pizza.pcic.uvic.ca:8003
```

If it's hitting the Gunicorn timeout, we should be seeing something like this in the backend log:

```
[2015-06-16 00:10:15 +0000] [9555] [CRITICAL] WORKER TIMEOUT
```

**Comment by mschnorb** [comment]
In my previous attempts I was downloading to local computer storage (and was getting warnings about low storage space). I've since changed my default download location to storage/home/mschnorb and I can download without problems. Looks like I wasn't putting two and two together (I just assumed the download would fail if there was insufficient storage). After some further inspection it seems I was trying to cram a 10GB file into 2.2GB of space! Apologies if this whole thing was a wild goose chase.

**Comment by jameshiebert** [comment]
Mystery solved! Yeah, weird that you didn't get an OS error, but that is not relevant to this ticket. Closing.
