### ISSUE TITLE
can't download from gridded hydrologic model output

### ISSUE THREAD

**Issue by AreliaTW** [pacificclimate/pdp#4]
Working on a Mac browsing with Safari under A2 for CCSM3 and Actual Evapotranspiration nothing happens when I click the Download or MetaData button after selecting NetCDF.

**Comment by basilveerman** [comment]
Closing with #5

**Comment by jameshiebert** [comment]
Should we leave this open until 2.3.0 is released?

**Comment by jameshiebert** [comment]
Fixed in 2.3.0
