### ISSUE TITLE
Improve config process and error message

### ISSUE THREAD

**Issue by jameshiebert** [pacificclimate/pdp#53]
At present, if a developer fails to provide a config file for pdp, you get this obnoxious error message:

```python
../../../virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/pdp/__init__.py:77: in wrap_auth

    config = get_config()

../../../virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/pdp/__init__.py:28: in get_config

    with open(config_filename) as f:

E   IOError: [Errno 2] No such file or directory: '/var/www/dataportal/config.yaml'
```

That stops you in your tracks. I think that we should consider either providing an in-package resource file for the default config, and just give a warning if it falls back to using it. Or at the very least, we should catch this `IOError` and give the user instructions on the fact that they need to provide a config file.

**Comment by CBMasri** [comment]
I think there's [already one](https://github.com/pacificclimate/pdp/blob/master/pdp/config.yaml) in there, that url just needs to be updated (those db links in the config should probably get updated too).

**Comment by jameshiebert** [comment]
It's in the repository, but it doesn't get built into the package (I don't think). One would have to include it as in the `pacakge_data` argument of `setup.py`. I'm not necessarily convinced that we *should* do that. Mostly, I just think that we should catch the IOError and explain to the user what they need to do to correct it.
