### ISSUE TITLE
Hyrologic Model Output portal gives 500 error on NetCDF downloads

### ISSUE THREAD

**Issue by CBMasri** [pacificclimate/pdp#55]
The hydro_model_out portal currently running in production is giving an internal server error (500) when you try and download a NetCDF dataset corresponding to any of the following climate variables:

- Base Flow
- Actual Evapotranspiration
- Column Total Soil Moisture
- Snow Water Equivalent
- Runoff

[Example](http://tools.pacificclimate.org/dataportal/data/hydro_model_out/5var_day_HadCM_A1B_run1_19500101-20991231.nc.nc?bf[0:54787][0:163][0:215]&) (A1B > HadCM > Base Flow)

The problem is only with `5var_day` NetCDF files, other output formats work as expected. It also couldn't be consistently replicated in dev, so it must be tied to the production environment. Possibly due to a MemoryError, but further investigation is needed.

**Comment by jameshiebert** [comment]
Appears to be fixed in new releases.
