### ISSUE TITLE
Error downloading VIC output data

### ISSUE THREAD

**Issue by tsurka01** [pacificclimate/pdp#61]
1) Went to http://tools.pacificclimate.org/dataportal/hydro_model_out/map/
2) Tried to download netcdf file of full time series of baseflow output from A1B, HadCM (http://tools.pacificclimate.org/dataportal/data/hydro_model_out/5var_day_HadCM_A1B_run1_19500101-20991231.nc.nc?bf[0:54787][0:163][0:215]&)
3) Expect firefox to open a download box dialogue
4) Instead received "file not found" error ("Firefox can’t find the file at http://tools.pacificclimate.org/dataportal/data/hydro_model_out/5var_day_HadCM_A1B_run1_19500101-20991231.nc.nc?bf[0:54787][0:163][0:215]&.")

-Had the same problem with attempts to download any other dataset from the VIC output, but had no problem downloading data from downscaled gcm scenarios (http://tools.pacificclimate.org/dataportal/downscaled_gcms/map/)

-Error occured at 4:15 pm PST

**Comment by jameshiebert** [comment]
I couldn't reproduce this in a clean development environment, so it wasn't a software bug. Server logs were showing memory errors a couple dozen hung processes. Restarting the backend data services seems to have cleaned everything up, so you *should* be able to download that dataset now.
