### ISSUE TITLE
Large PCDS downloads result in corrupt zip files

### ISSUE THREAD

**Issue by jameshiebert** [pacificclimate/pdp#62]
From @faronium:

>A user recently contacted me indicating that a zip file he had downloaded was corrupted and indicated that the size was ~400MB. I responded suggesting that it was possible that he had tried to open the file before it had completed downloading. But, I tested to make sure and got the same result. In my case I selected a region around Vancouver and downloaded a file of ~270MB in size and was informed that it was corrupt both within linux and windows.

**Comment by jameshiebert** [comment]
Using [this URL](http://tools.pacificclimate.org/dataportal/data/pcds/agg/?from-date=YYYY%2FMM%2FDD&to-date=YYYY%2FMM%2FDD&input-polygon=MULTIPOLYGON(((-129.5849491508835+51.03226748851107%2C-127.44876628215732+48.66560990424601%2C-122.87059000701385+47.86874017464353%2C-122.17312254815441+49.18683607245565%2C-127.38367257725528+51.55889666575661%2C-129.5849491508835+51.03226748851107)))&input-var=&network-name=&input-freq=&data-format=nc&metadata-format=csv) (CSV output, polygon filter around Vancouver Island, no other filters) as a test case.

**Comment by jameshiebert** [comment]
Not sure if it's related, but I noticed a number of errors in the logs during the above request:
```
[Mon Mar 27 12:16:08 2017] [error] [client 127.0.1.1] (70014)End of file found: Error reading chunk  
[Mon Mar 27 12:18:53 2017] [error] [client 127.0.1.1] (70014)End of file found: Error reading chunk  
[Mon Mar 27 12:20:47 2017] [error] [client 127.0.1.1] (70014)End of file found: Error reading chunk  
[Mon Mar 27 12:23:42 2017] [error] [client 127.0.1.1] (70014)End of file found: Error reading chunk  
[Mon Mar 27 12:26:47 2017] [error] [client 127.0.1.1] (70014)End of file found: Error reading chunk  
```
It could be related to [this known issue](https://github.com/pacificclimate/pdp_util/issues/1) in ``pdp_util`` as well...

**Comment by corviday** [comment]
[A small test case](http://tools.pacificclimate.org/dataportal/data/pcds/agg/?from-date=YYYY%2FMM%2FDD&to-date=YYYY%2FMM%2FDD&input-polygon=MULTIPOLYGON%28%28%28-125.29637443283997+49.75425334879682%2C-125.27276223016982+49.757216316386696%2C-125.27059060328506+49.742548670551834%2C-125.29276284376195+49.73895329426124%2C-125.29637443283997+49.75425334879682%29%29%29&input-var=&network-name=&input-freq=&data-format=ascii&download-timeseries=Timeseries
).

This polygon encompasses three adjacent `EC` or` EC_raw` stations on top of Mount Washington near Comox. The sidebar to the right says "4 stations / 26k observations / 37 climatologies" but only three stations appear in the map or the downloadable metadata. Downloading a timeseries results in a corrupted zip file.

In the database, there is a fourth station in the vicinity (station id 11764) with no `min_obs_time` or `max_obs_time`, which supports @jameshiebert's suggestion that stations with no observations might be the issue.

**Comment by corviday** [comment]
Modified the query in `util.get_stn_list` to exclude stations whose `min_obs_time` was NULL. This doesn't actually fix the problem, oddly.
Here's the original query run in util.get_stn_list to create a list of stations for display or download (using the small test case above):
```
SELECT crmp_network_geoserver.network_name AS crmp_network_geoserver_network_name, crmp_network_geoserver.native_id AS crmp_network_geoserver_native_id 
FROM crmp_network_geoserver 
WHERE ST_intersects(ST_GeomFromText('MULTIPOLYGON(((-125.29637443283997 49.75425334879682,-125.27276223016982 49.757216316386696,-125.27059060328506 49.742548670551834,-125.29276284376195 49.73895329426124,-125.29637443283997 49.75425334879682)))', 4326), the_geom)

```
Which returns the following four stations:
```
[(u'EC_raw', u'1025230'), 
(u'EC', u'1025237'), 
(u'EC', u'1025234'), 
(u'EC', u'1025230')]
```

Modifying the query to exclude stations with no `min_obs_time` like this:
```
SELECT crmp_network_geoserver.network_name AS crmp_network_geoserver_network_name, crmp_network_geoserver.native_id AS crmp_network_geoserver_native_id 
FROM crmp_network_geoserver 
WHERE ST_intersects(ST_GeomFromText('MULTIPOLYGON(((-125.29637443283997 49.75425334879682,-125.27276223016982 49.757216316386696,-125.27059060328506 49.742548670551834,-125.29276284376195 49.73895329426124,-125.29637443283997 49.75425334879682)))', 4326), the_geom) 
AND min_obs_time IS NOT NULL
```
returns these three stations:
```
[(u'EC_raw', u'1025230'), 
(u'EC', u'1025237'), 
(u'EC', u'1025234')]
```
Missing from the second set is `EC 1025230`, which has a NULL `min_obs_time`.
Still present in the second set is `EC_Raw 1025230`, which _also_ has a NULL `min_obs_time`. 

```
crmp=>select * from meta_station WHERE min_obs_time IS NULL AND native_id = '1025230';
 station_id | network_id | native_id | min_obs_time | max_obs_time 
------------+------------+-----------+--------------+--------------
       6616 |         19 | 1025230   |              | 
      11764 |          1 | 1025230   |              | 
(2 rows)
```
Writing EC_Raw 1025230 to the zipfile seems to cause an error in sqlalchemy that brings the zipfile creation process to a halt, resulting in an incomplete file.

**Comment by jameshiebert** [comment]
Soooo, this is a little horrible, but it turns out that ``meta_station.min_obs_time`` and `meta_station.max_obs_time`` are an artefact of a previous era and are *not* actually used for anything anymore. We should remove them from the schema and from [PyCDS](https://github.com/pacificclimate/pycds/blob/master/pycds/__init__.py#L84) to eliminate this possible source of confusion.

Note that if you trace back from the ``crmp_network_geoserver`` view, you'll see that those columns come from a materialized view named ``station_obs_stats`` defined as such:

```SQL
crmp=> \d+ station_obs_stats_v
                        View "crmp.station_obs_stats_v"
    Column    |            Type             | Modifiers | Storage | Description 
--------------+-----------------------------+-----------+---------+-------------
 station_id   | integer                     |           | plain   | 
 history_id   | integer                     |           | plain   | 
 min_obs_time | timestamp without time zone |           | plain   | 
 max_obs_time | timestamp without time zone |           | plain   | 
 obs_count    | bigint                      |           | plain   | 
View definition:
 SELECT meta_history.station_id, foo.history_id, foo.min_obs_time, foo.max_obs_time, foo.obs_count
   FROM ( SELECT min(obs_raw.obs_time) AS min_obs_time, max(obs_raw.obs_time) AS max_obs_time, obs_raw.history_id, count(DISTINCT obs_raw.obs_time) AS obs_count
           FROM obs_raw
          GROUP BY obs_raw.history_id) foo
NATURAL JOIN meta_history;
```

So you'll probably want to adjust your debugging query above to directly use ``crmp_network_geoserver`` (like the code does) and to *not* use ``meta_station`` directly.

**Comment by corviday** [comment]
Thanks, that's much less confusing.

**Comment by corviday** [comment]
A database anomaly I think could be complicating the issue: station` EC_Raw 1025230` (distinct from `EC 1025230`) is using observation variables from the EC network, not the EC_Raw network.

```
crmp=> SELECT history_id, station_id, station_name FROM meta_history 
crmp-> WHERE station_id = 6616 OR station_id = 11764; 

 history_id | station_id |   station_name   
------------+------------+------------------
       8301 |       6616 | Mount Washington
      13819 |      11764 | MT WASHINGTON
(2 rows)

crmp=> SELECT history_id, count (*) FROM obs_raw where history_id = 8301
crmp-> OR history_id = 13819 GROUP BY history_id;
 history_id | count 
------------+-------
       8301 |  3393


crmp=> SELECT DISTINCT history_id, vars_id FROM obs_raw WHERE history_id = 8301;
------------+---------
       8301 |     430
       8301 |     429
       8301 |     432
       8301 |     428
       8301 |     427
(5 rows)

crmp=> SELECT vars_id, network_id, display_name FROM meta_vars
crmp-> WHERE vars_id > 426 AND vars_id < 433;
 vars_id | network_id |        display_name        
---------+------------+----------------------------
     429 |          1 | Precipitation Amount
     427 |          1 | Temperature (Min.)
     431 |          1 | Snowfall Amount
     428 |          1 | Temperature (Max.)
     430 |          1 | Rainfall Amount
     432 |          1 | Surface Snow Depth (Point)
(6 rows)
```
That is, EC_Raw 1025230 is associated with network 19 (EC_Raw), but all of its observations are associated with network 1 (EC).

Here's the error generated in PDP when you try to download data from this station, which includes the query it is trying to run:

```
E   ProgrammingError: (ProgrammingError) column "one_day_precipitation" does not exist
E   LINE 1: SELECT ONE_DAY_PRECIPITATION, ONE_DAY_RAIN, obs_time, MIN_TE...
E                  ^
E    'SELECT ONE_DAY_PRECIPITATION, ONE_DAY_RAIN, obs_time, MIN_TEMP, MAX_TEMP, SNOW_ON_THE_GROUND FROM (SELECT obs_time,MAX(CASE WHEN vars_id=542 THEN datum END) as air_temperature,MAX(CASE WHEN vars_id=544 THEN datum END) as air_temperature_yesterday_high,MAX(CASE WHEN vars_id=545 THEN datum END) as air_temperature_yesterday_low,MAX(CASE WHEN vars_id=551 THEN datum END) as dew_point,MAX(CASE WHEN vars_id=549 THEN datum END) as mean_sea_level,MAX(CASE WHEN vars_id=552 THEN datum END) as relative_humidity,MAX(CASE WHEN vars_id=548 THEN datum END) as snow_amount,MAX(CASE WHEN vars_id=555 THEN datum END) as tendency_amount,MAX(CASE WHEN vars_id=554 THEN datum END) as total_cloud_cover,MAX(CASE WHEN vars_id=546 THEN datum END) as total_precipitation,MAX(CASE WHEN vars_id=547 THEN datum END) as total_rain,MAX(CASE WHEN vars_id=553 THEN datum END) as wind_direction,MAX(CASE WHEN vars_id=543 THEN datum END) as wind_gust_speed,MAX(CASE WHEN vars_id=550 THEN datum END) as wind_speed from obs_raw WHERE (history_id = 8301) AND vars_id IN (542,544,545,551,549,552,548,555,554,546,547,553,543,550) GROUP BY obs_time ORDER BY obs_time) as foo LIMIT 1' {}
```
PDP querying on `vars_ids` from 542 to 554, all of which are associated with the EC_Raw network, `network_id 19`:

crmp=> SELECT vars_id, network_id, display_name FROM meta_vars
crmp-> WHERE vars_id > 541 AND vars_id < 555;
 vars_id | network_id |         display_name          
---------+------------+-------------------------------
     542 |         19 | Temperature (Point)
     543 |         19 | Wind Gust (Max.)
     545 |         19 | Temperature (Min.)
     544 |         19 | Temperature (Max.)
     551 |         19 | Dew Point Temperature (Point)
     550 |         19 | Wind Speed (Point)
     548 |         19 | Snowfall Amount
     549 |         19 | Mean Sea Level
     552 |         19 | Relative Humidity (Point)
     547 |         19 | Rainfall Amount
     553 |         19 | Wind Direction (Mean)
     554 |         19 | Cloud Cover Fraction
     546 |         19 | Precipitation Amount
(13 rows)

**Comment by corviday** [comment]
I've poked at the rest of the EC_Raw network, and this issue seems to only affect EC_Raw 1025230.

**Comment by jameshiebert** [comment]
Wow, good catch! That would definitely do it. Can you investigate which network the observations and station *should* be associated with? You might want to chat with @faronium on this issue.

**Comment by corviday** [comment]
I've verified that this specific issue does not occur anywhere else in the test database.

**Comment by jameshiebert** [comment]
With @corviday having corrected the data errors in the database, I think that we can safely close this issue. The [test case](http://tools.pacificclimate.org/dataportal/data/pcds/agg/?from-date=YYYY%2FMM%2FDD&to-date=YYYY%2FMM%2FDD&input-polygon=MULTIPOLYGON%28%28%28-122.84250052310462+49.33095465473638%2C-122.90005834526038+49.297649140301004%2C-122.86157366135+49.24657317992617%2C-122.76249620948452+49.219908575081675%2C-122.66148902126935+49.24806074593272%2C-122.70891368322285+49.30448396541877%2C-122.84250052310462+49.33095465473638%29%29%29&input-var=&network-name=&input-freq=&data-format=ascii&download-timeseries=Timeseries) passes with station 1025230 being returned properly. Feel free to reopen if you run into this problem again, but I think that we can consider this case closed. Good job all!

**Comment by jameshiebert** [comment]
Nevermind, Lee's [third test case](http://tools.pacificclimate.org/dataportal/data/pcds/agg/?from-date=YYYY%2FMM%2FDD&to-date=YYYY%2FMM%2FDD&input-polygon=MULTIPOLYGON%28%28%28-122.84250052310462+49.33095465473638%2C-122.90005834526038+49.297649140301004%2C-122.86157366135+49.24657317992617%2C-122.76249620948452+49.219908575081675%2C-122.66148902126935+49.24806074593272%2C-122.70891368322285+49.30448396541877%2C-122.84250052310462+49.33095465473638%29%29%29&input-var=&network-name=&input-freq=&data-format=ascii&download-timeseries=Timeseries) still errors out...

**Comment by corviday** [comment]
It seems like there may be a second database anomaly affecting the MVan (Metro Vancouver) network, which is responsible for the failure of the third test case. As far as I can tell, downloading any polygon containing a MVan station without specifying beginning and ending dates will result in a corrupted zipfile. 

I haven't yet pinned down why this happens. No station in this network is associated with any observations, but it doesn't seem likely that alone would cause the issue, since @jameshiebert found stations without observations that download correctly, such as Kelp Reefs (EC 1013998), or all the FLNRO-FERN stations on Vancouver island.

Every station _not_ on the MVan network downloads correctly, whether it has associated observations or not. Zipfile corruption happens if and only if a MVan station is included in the download. So probably another database fix, not a code fix, as soon as I track down what's off about that network.
