### ISSUE TITLE
Downloaded data is all for year 2000, even with date filter

### ISSUE THREAD

**Issue by sharynalexander** [pacificclimate/pdp#63]
Hi, I'm trying to download climatology data for a certain date range (2012-2016). After several times downloading climatology data in both CSV/Ascii and MS Excel outputs, I notice they all seem to have a 'time' of '2000', e.g., "2000-10-31", which appears to be the date. 

I've tried to download both with a date filter and without, without using the zoom or other map functions. Does this mean there only is climatology data available for the year 2000 or is there another way to access more recent data?
thanks

**Comment by jameshiebert** [comment]
Hi @sharynalexander. Can you provide a few more details. From which dataset are you trying to download: [the Provincial Climate Data Set](http://tools.pacificclimate.org/dataportal/pcds/map/) or the [BC PRISM climatologies](http://tools.pacificclimate.org/dataportal/bc_prism/map/). Can you tell us more about the filters that you're using or the dataset selection or anything other information to pinpoint which data exactly you are targeting?

**Comment by sharynalexander** [comment]
Hi, basically I'd like temperature data for an area in northeastern BC over
the periods 2012-2016. I went to the portal (
http://tools.pacificclimate.org/dataportal/pcds/map/) and under 'Download
Data' selected CSV/Ascii output and clicked Climatology. I got a series of
ascii text files from the various stations, but they all seem to have a
time/date of '2000' (attached).

I also tried downloading MS Excel 2010 output, and using the date filter
under 'Filter Options'.

Thanks for your help!
sharyn

**Comment by jameshiebert** [comment]
Hi Sharyn,

If you really do want the *climatologies* of the stations over northeastern BC, those are basically 30-year means (1971-2000 I believe). So asking for data from the 4 year period 2012-2016 isn't compatible with a request for climatologies. If you are specifically interested in that 4 year period, I would suggest that you uncheck the "Climatology" checkbox, download the raw data and compute your own means.

**Comment by sharynalexander** [comment]
Hi James, I do not have the climatologies box ticked (for those results 1971-2000), and the only option to download data is by clicking the 'Climatology' button or the 'Timeseries' button. There is also a tick box to 'Clip time series to filter date range' which have tried ticked and unticked.
Please advise how to download the raw data as it appears to only have options to download the Climatology or Timeseries data.
thanks!
![image](https://cloud.githubusercontent.com/assets/26940827/24924764/c325225c-1eaa-11e7-8135-f0d60c4fa289.png)

**Comment by jameshiebert** [comment]
Use the "Timeseries" button for raw observations.
