### ISSUE TITLE
Datepicker on raster portals ignores calendars

### ISSUE THREAD

**Issue by jameshiebert** [pacificclimate/pdp#64]
From @ssobie:

> Hi James,
> 
> There appears to be an issue in the BCCAQ data portal when attempting to download a subset of a time series from a downscaled model rather than
> +the full range of data. I've attempted to download 1971-01-01 to 2070-12-30 for HaGEM2-ES for a site in Newfoundland (as per the emails below).
> +The date range I get from the selected file is then: 1971-04-21 to 2072-10-05.
> 
> In the data portal time selection the maximum date available for this model is also 2097-11-05, though if you download the entire series you get
> +the correct range of 1950-01-01 to 2099-12-30.
> 
> 
> This looks like an issue for the other models as well, with the maximum date for 365-day calendar models being 2100-11-25 instead of 2100-12-31. I
> +think the portal must be assuming a gregorian calendar in how it presents the data time.
> 
> Cheers,
> 
> Stephen

**Comment by jameshiebert** [comment]
Related to #59

**Comment by jameshiebert** [comment]
First thing to keep in mind with respect to this issue is that OPeNDAP doesn't have any awareness of dates. Its knowledge of datasets is essentially just an array with 0-based indices. So requests to an OPeNDAP server (i.e. the requests from our web-front-end to the data server backend) are responsible for doing their own conversion from dates to array indices. We do not do this, at this time.

Our [JavaScript date picker](https://jqueryui.com/datepicker/) has no knowledge of different calendar types (i.e. 365-day and 360-day calendars), since this is a oddity reserved for solely for climate modelling.

Fixing this issue in our front-end code, would require a few additions to our [CfTime class](https://github.com/pacificclimate/pdp/blob/master/pdp/static/js/pdp_raster_map.js#L7), to take the calendar into account when computing indices.

**Comment by jameshiebert** [comment]
FWIW, the reason that we have not prioritized this in the past is because [85% of our requests on the raster portals](https://github.com/pacificclimate/pdp/issues/27) have been for the full timeseries (and thus are unaffected by this bug). Only [2% of requests](https://github.com/pacificclimate/pdp/issues/27) have been for partial timeseries on non-standard calendars).

So @corviday don't spend a *ton* of time on this request. A quick-and-dirty fix is sufficient.

**Comment by ssobie** [comment]
There seems to be a further issue when downloading a full series as Arc/Info ASCII grid format (which I think is how the user in this case requested the data). The output when requesting a full time series for HadGEM2-ES is 32767 individual files. This doesn't correspond to the number of timesteps which should be 54000. I'm not sure where this number is coming from and whether is means the data is somehow truncated.

**Comment by jameshiebert** [comment]
Hmmmm, 32767 is 2^16-1 so I'd suspect that it's some problem where code is using a short integer rather than s long. This would be a separate issue, and should be filed against pacificclimate/pydap.responses.aaigrid.

**Comment by jameshiebert** [comment]
Yep, looks like I probably [reported the Arc/Info issue](https://github.com/pacificclimate/pydap.responses.aaigrid/issues/2) last fall. So feel free to track and/or comment on the issue over at the other repo.

**Comment by jameshiebert** [comment]
Just a quick observation here, as of today, all of the BCSD downscaled model output is attributed with "standard" calendar (even though the time variable length makes it clear that some are 365 and some are 360 day calendars). So even if we fix the software to respect alternative calendars, we'll need to also correct some metadata.

```
hiebert@cheetah:/storage/data/climate/downscale/CMIP5/BCSD$ for i in *.nc; do echo $i; ncdump -h $i | egrep "(calendar|time =)"; done
pr+tasmax+tasmin_day_BCSD+ANUSPLIN300+ACCESS1-0_historical+rcp45_r1i1p1_19500101-21001231.nc
	time = UNLIMITED ; // (55152 currently)
		time:calendar = "standard" ;
pr+tasmax+tasmin_day_BCSD+ANUSPLIN300+ACCESS1-0_historical+rcp85_r1i1p1_19500101-21001231.nc
	time = UNLIMITED ; // (55152 currently)
		time:calendar = "standard" ;
pr+tasmax+tasmin_day_BCSD+ANUSPLIN300+CanESM2_historical+rcp26_r1i1p1_19500101-21001231.nc
	time = UNLIMITED ; // (55152 currently)
		time:calendar = "standard" ;
pr+tasmax+tasmin_day_BCSD+ANUSPLIN300+CanESM2_historical+rcp45_r1i1p1_19500101-21001231.nc
	time = UNLIMITED ; // (55152 currently)
		time:calendar = "standard" ;
pr+tasmax+tasmin_day_BCSD+ANUSPLIN300+CanESM2_historical+rcp85_r1i1p1_19500101-21001231.nc
	time = UNLIMITED ; // (55152 currently)
		time:calendar = "standard" ;
pr+tasmax+tasmin_day_BCSD+ANUSPLIN300+CCSM4_historical+rcp26_r2i1p1_19500101-21001231.nc
	time = UNLIMITED ; // (55152 currently)
		time:calendar = "standard" ;
pr+tasmax+tasmin_day_BCSD+ANUSPLIN300+CCSM4_historical+rcp45_r2i1p1_19500101-21001231.nc
	time = UNLIMITED ; // (55152 currently)
		time:calendar = "standard" ;
pr+tasmax+tasmin_day_BCSD+ANUSPLIN300+CCSM4_historical+rcp85_r2i1p1_19500101-21001231.nc
	time = UNLIMITED ; // (55152 currently)
		time:calendar = "standard" ;
pr+tasmax+tasmin_day_BCSD+ANUSPLIN300+CNRM-CM5_historical+rcp26_r1i1p1_19500101-21001231.nc
	time = UNLIMITED ; // (55152 currently)
		time:calendar = "standard" ;
pr+tasmax+tasmin_day_BCSD+ANUSPLIN300+CNRM-CM5_historical+rcp45_r1i1p1_19500101-21001231.nc
	time = UNLIMITED ; // (55152 currently)
		time:calendar = "standard" ;
pr+tasmax+tasmin_day_BCSD+ANUSPLIN300+CNRM-CM5_historical+rcp85_r1i1p1_19500101-21001231.nc
	time = UNLIMITED ; // (55152 currently)
		time:calendar = "standard" ;
pr+tasmax+tasmin_day_BCSD+ANUSPLIN300+CSIRO-Mk3-6-0_historical+rcp26_r1i1p1_19500101-21001231.nc
	time = UNLIMITED ; // (55152 currently)
		time:calendar = "standard" ;
pr+tasmax+tasmin_day_BCSD+ANUSPLIN300+CSIRO-Mk3-6-0_historical+rcp45_r1i1p1_19500101-21001231.nc
	time = UNLIMITED ; // (55152 currently)
		time:calendar = "standard" ;
pr+tasmax+tasmin_day_BCSD+ANUSPLIN300+CSIRO-Mk3-6-0_historical+rcp85_r1i1p1_19500101-21001231.nc
	time = UNLIMITED ; // (55152 currently)
		time:calendar = "standard" ;
pr+tasmax+tasmin_day_BCSD+ANUSPLIN300+GFDL-ESM2G_historical+rcp26_r1i1p1_19500101-21001231.nc
	time = UNLIMITED ; // (55152 currently)
		time:calendar = "standard" ;
pr+tasmax+tasmin_day_BCSD+ANUSPLIN300+GFDL-ESM2G_historical+rcp45_r1i1p1_19500101-21001231.nc
	time = UNLIMITED ; // (55152 currently)
		time:calendar = "standard" ;
pr+tasmax+tasmin_day_BCSD+ANUSPLIN300+GFDL-ESM2G_historical+rcp85_r1i1p1_19500101-21001231.nc
	time = UNLIMITED ; // (55152 currently)
		time:calendar = "standard" ;
pr+tasmax+tasmin_day_BCSD+ANUSPLIN300+HadGEM2-CC_historical+rcp45_r1i1p1_19500101-20991230.nc
	time = UNLIMITED ; // (54787 currently)
		time:calendar = "standard" ;
pr+tasmax+tasmin_day_BCSD+ANUSPLIN300+HadGEM2-CC_historical+rcp85_r1i1p1_19500101-20991230.nc
	time = UNLIMITED ; // (54787 currently)
		time:calendar = "standard" ;
pr+tasmax+tasmin_day_BCSD+ANUSPLIN300+HadGEM2-ES_historical+rcp26_r1i1p1_19500101-21001230.nc
	time = UNLIMITED ; // (55152 currently)
		time:calendar = "standard" ;
pr+tasmax+tasmin_day_BCSD+ANUSPLIN300+HadGEM2-ES_historical+rcp45_r1i1p1_19500101-21001230.nc
	time = UNLIMITED ; // (55152 currently)
		time:calendar = "standard" ;
pr+tasmax+tasmin_day_BCSD+ANUSPLIN300+HadGEM2-ES_historical+rcp85_r1i1p1_19500101-20991230.nc
	time = UNLIMITED ; // (54787 currently)
		time:calendar = "standard" ;
pr+tasmax+tasmin_day_BCSD+ANUSPLIN300+inmcm4_historical+rcp45_r1i1p1_19500101-21001231.nc
	time = UNLIMITED ; // (55152 currently)
		time:calendar = "standard" ;
pr+tasmax+tasmin_day_BCSD+ANUSPLIN300+inmcm4_historical+rcp85_r1i1p1_19500101-21001231.nc
	time = UNLIMITED ; // (55152 currently)
		time:calendar = "standard" ;
pr+tasmax+tasmin_day_BCSD+ANUSPLIN300+MIROC5_historical+rcp26_r3i1p1_19500101-21001231.nc
	time = UNLIMITED ; // (55152 currently)
		time:calendar = "standard" ;
pr+tasmax+tasmin_day_BCSD+ANUSPLIN300+MIROC5_historical+rcp45_r3i1p1_19500101-21001231.nc
	time = UNLIMITED ; // (55152 currently)
		time:calendar = "standard" ;
pr+tasmax+tasmin_day_BCSD+ANUSPLIN300+MIROC5_historical+rcp85_r3i1p1_19500101-21001231.nc
	time = UNLIMITED ; // (55152 currently)
		time:calendar = "standard" ;
pr+tasmax+tasmin_day_BCSD+ANUSPLIN300+MPI-ESM-LR_historical+rcp26_r3i1p1_19500101-21001231.nc
	time = UNLIMITED ; // (55152 currently)
		time:calendar = "standard" ;
pr+tasmax+tasmin_day_BCSD+ANUSPLIN300+MPI-ESM-LR_historical+rcp45_r3i1p1_19500101-21001231.nc
	time = UNLIMITED ; // (55152 currently)
		time:calendar = "standard" ;
pr+tasmax+tasmin_day_BCSD+ANUSPLIN300+MPI-ESM-LR_historical+rcp85_r3i1p1_19500101-21001231.nc
	time = UNLIMITED ; // (55152 currently)
		time:calendar = "standard" ;
pr+tasmax+tasmin_day_BCSD+ANUSPLIN300+MRI-CGCM3_historical+rcp26_r1i1p1_19500101-21001231.nc
	time = UNLIMITED ; // (55152 currently)
		time:calendar = "standard" ;
pr+tasmax+tasmin_day_BCSD+ANUSPLIN300+MRI-CGCM3_historical+rcp45_r1i1p1_19500101-21001231.nc
	time = UNLIMITED ; // (55152 currently)
		time:calendar = "standard" ;
pr+tasmax+tasmin_day_BCSD+ANUSPLIN300+MRI-CGCM3_historical+rcp85_r1i1p1_19500101-21001231.nc
	time = UNLIMITED ; // (55152 currently)
		time:calendar = "standard" ;
```
