### ISSUE TITLE
Date range in downloaded file names doesn't match range contained in file

### ISSUE THREAD

**Issue by corviday** [pacificclimate/pdp#67]
When downloading a file with a user-specified date range from the downscaled gcm scenario portal, the date range given in the filename is the minimum and maximum dates available for that dataset, not the range requested by the user or contained in the file itself.

**Steps to reproduce:**
1. Go to the [downscaled gcms portal](http://tools.pacificclimate.org/dataportal/downscaled_gcms/map/)
2. Input a date range in the "download data" sidebar, such as 1/1/1950 to 1/2/1950
3. Click the "Download" link.

The filename will be:

`pr+tasmax+tasmin_day_BCSD+ANUSPLIN300+CanESM2_historical+rcp26_r1i1p1_19500101-21001231.nc.nc`

which reflects the minimum (1950/01/01) and maximum (2100/12/31) range of the entire dataset, not the range requested. The contents of the file will match the requested range.

**Comment by jameshiebert** [comment]
Filenames are not an authoritative source of metadata. Consider them "guidance" or an approximation. Don't actually use it for anything or trust it to be fact.
