### ISSUE TITLE
UI tweaks for Gridded Obs portal

### ISSUE THREAD

**Issue by jameshiebert** [pacificclimate/pdp#73]
A few UI tweaks have been suggested by our director:

- [x] Change [dataset label](https://github.com/pacificclimate/pdp/blob/master/pdp/portals/gridded_observations.py#L22) "TPS" to something else (possibly "VIC-GL Forcings"). Still under consideration.
- [x] Add the date shown on the map to the [map title](https://github.com/pacificclimate/pdp/blob/master/pdp/static/js/gridded_observations_map.js#L75) as we have done in [other portals](https://github.com/pacificclimate/pdp/blob/master/pdp/static/js/canada_ex_map.js#L102)
- [x] Pick a different [default date](https://github.com/pacificclimate/pdp/blob/master/pdp/portals/gridded_observations.py#L22) that has some precipitation going on

**Comment by corviday** [comment]
I'm having some trouble finding a default date with high contract precipitation variation; these datasets seem to have a pretty large difference between maximum and median precipitation values.

**Comment by jameshiebert** [comment]
That looks like a linear color scale. Can you add a log scale for `pr` like we do in the other portal frontends?

**Comment by corviday** [comment]
Good idea, thanks.

**Comment by corviday** [comment]
- [ ] Arelia has requested the displayed name of the TPS dataset be changed to PNWNAmet
