### ISSUE TITLE
Unable to view station meta data

### ISSUE THREAD

**Issue by faronium** [pacificclimate/pdp#86]
Seems to be an issue in the portal where neither clicking on a station symbol on the map nor clicking the "View Metadata" button yields any results. The former just doesn't work and the latter opens the light box and gives a "loading..." message that lasts forever. This may be an issue on the back end as some cron jobs that read from the database returned empty tables yesterday morning. I don't have logs on those jobs so can't help diagnose why. Running them this morning seems to work.

**Comment by jameshiebert** [comment]
Thanks for catching this! We've migrated the data portal on to compute canada servers, but the metadata requests are still directed back to our servers (Geoserver on tools.pacificclimate.org). If one looks in the dev tools, one can see that the metadata request is going through and succeeding, but then the browser blocks the content as a "cross origin" request.

E.g.

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://tools.pacificclimate.org/geoserver/CRMP/wms?REQUEST=GetFeatureInfo&EXCEPTIONS=application%2Fvnd.ogc.se_xml&SERVICE=WMS&VERSION=1.1.0&INFO_FORMAT=text%2Fhtml&FORMAT=image%2Fpng&BBOX=-627679.25%2C498665.75%2C2595801.25%2C1490335.25&X=357&Y=193&QUERY_LAYERS=CRMP%3Acrmp_network_geoserver&FEATURE_COUNT=5&LAYERS=CRMP%3Acrmp_network_geoserver&WIDTH=1453&HEIGHT=447&SRS=EPSG%3A3005&BUFFER=10. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
```

There are a couple ways to solve this through deployment proxying, but it's not a problem with the underlying data or necessarily the pdp software.

**Comment by jameshiebert** [comment]
We've set cross origin headers on Geoserver allowing the cross origin request to be allowed. You should be good to go here.
