### ISSUE TITLE
Help wanted / server down?

### ISSUE THREAD

**Issue by masonfried** [pacificclimate/pdp#95]
Dear PCIC Data Portal Help,

I am unable to download netCDF's from PCIC's statistically downscaled GCM scenarios. 

First I opened the option to "Access and download Statistically Downscaled GCM Scenarios" (https://data.pacificclimate.org/portal/downscaled_gcms/map/). In the map view portal I first selected a rectangular query box over my desired data area. Then I made my dataset selection (historical+rcp85; BCCAQ+ANUSPLIN300+HadGEM2-ES; tasmax). I then chose my date range (1 Jan 2010 to 1 Jan 2051). Finally I selected my desired output format (NetCDF) and requested a download.

Upon multiple requests the dataset failed to download. Each download file returned either "Failed - File incomplete", or "Failed - Server problem." I attempted to download using both Chrome and Safari browsers and multiple networks. I expected the netCDFs to download containing the data query I assigned in the portal, but the downloads failed.

My IP address is, IPv4: 199.223.30.254.

Can you please advise as to what might be the problem? Is the server down on your end or perhaps I am not querying the data properly? 

I greatly appreciate your help and thank you in advance for your assistance. This is a wonderful dataset and I look forward to using it.

Best,
Mason Fried
ICF International

**Comment by corviday** [comment]
Dear Mason,

I'm sorry you had trouble. This error was caused by our data portal website being too busy and overloaded. We've just upgraded our hosting, so hopefully things should be working better now. Please try again and let me know if you are still having trouble.

Thanks!
