### ISSUE TITLE
date range selector in Statistically Downscaled GCM Scenarios Map Portal

### ISSUE THREAD

**Issue by mk289** [pacificclimate/pdp#96]
When I try to download a selection based on date (for any 8.5 rcp BCCAQ scenario datasets) I get a retrieval incomplete error in any web browser (firefox, chrome etc.) even on small areas.  If I download the full span of years however it does work.  If you could resolve this that would be great!  Thanks.

**Comment by jameshiebert** [comment]
I was able to download a BCCAQ 8.5 RCP scenario just fine:

**Comment by mk289** [comment]
Ok, must be something wrong on my end.  Thanks for looking into it!

**Comment by jameshiebert** [comment]
Yeah, no problem. Sorry that it took us so long to check it out!
