### ISSUE TITLE
Gateway time-out when attempting to download data

### ISSUE THREAD

**Issue by grahamatjasco** [pacificclimate/pdp#97]
I went to: https://data.pacificclimate.org/portal/pcds/map/
Then zoomed in to Saturna Island, BC. Then selected STATION:6648 with the polygon tool in the top-right corner. Filtered the data by...

Date Range: 2016-01-01 to 2018-01-01
Climate Variables: Precipitation Amount
Network Name: All
Observation Frequency: Hourly

Tried to download Timeseries data for Output Format CSV/ASCII and the bottom bar on the browser said "waiting for data.pacificclimate.org" and after about 1 minute, the browser took me to a white page that said:

504 Gateway Time-out
The server didn't respond in time.

I was expecting to download a CSV file with precipitation data from the selected station. I tried this between 10:00 and 10:30 AM, PST, on November 27, 2018. My IP address is 208.98.206.26. Using Google Chrome Version 70.0.3538.102 (Official Build) (64-bit).

**Comment by corviday** [comment]
Sorry you had trouble. This error was caused by the data portal being too busy. We've recently upgraded the hosting for the data portal, which should hopefully fix this problem. Please try again and let me know.
